INSERT INTO Reviews (userName, resName, revRating)
VALUES
    ('gourmet_guru', 'Smokehouse BBQ', 4.5),
    ('bbq_master', 'Smokehouse BBQ', 4.8),
    ('flavor_fanatic', 'Smokehouse BBQ', 4.2),
    ('spice_seeker', 'Smokehouse BBQ', 4.6),
    ('herbivore_haven', 'Smokehouse BBQ', 4.9),
    ('culinary_adventurer', 'Smokehouse BBQ', 4.4),
    ('bakery_buff', 'Smokehouse BBQ', 4.7),
    
    ('breakfast_lover', 'Rise & Shine Eats', 4.6),
    ('taste_traveller', 'Rise & Shine Eats', 4.3),
    ('creative_user50', 'Rise & Shine Eats', 4.5),
    
    ('coffee_craze', 'Coffee Corner', 4.9),
    ('creative_user50', 'Coffee Corner', 4.8),
    ('flavor_fanatic', 'Coffee Corner', 4.5),

    ('creative_user50', 'Creative Cuisine', 4.7),
    ('flavor_fanatic', 'Creative Cuisine', 4.5),
    ('mediterranean_meanderer', 'Creative Cuisine', 4.8),
    ('pizza_pal', 'Creative Cuisine', 4.6),
    ('coffee_craze', 'Creative Cuisine', 4.4),
    ('gourmet_guru', 'Creative Cuisine', 3.6),
    ('spice_seeker', 'Creative Cuisine', 4.6),

    ('farm_to_table', 'Farm-to-Table Eats', 4.9),
    ('noodle_navigator', 'Farm-to-Table Eats', 4.7),
    ('spice_seeker', 'Farm-to-Table Eats', 4.5),
    ('juice_junkie', 'Farm-to-Table Eats', 4.8),
    ('culinary_adventurer', 'Farm-to-Table Eats', 4.6),
    ('sushi_sensei', 'Farm-to-Table Eats', 4.6),
    
    ('gourmet_guru', 'Taco Palace', 4.8),
    ('culinary_adventurer', 'Taco Palace', 4.5),
    ('spice_seeker', 'Taco Palace', 3.2),
    ('flavor_fanatic', 'Taco Palace', 4.9),
    ('sushi_sensei', 'Taco Palace', 4.7),

    ('fusion_fanatic', 'Fiery Bites', 4.6),
    ('spice_aficionado', 'Fiery Bites', 4.3),
    ('flavor_fanatic', 'Fiery Bites', 4.8),
    ('veggie_voyager', 'Fiery Bites', 4.5),
    ('culinary_adventurer', 'Fiery Bites', 4.7),

    ('fusion_fanatic', 'Greek Delights', 4.6),
    ('creative_user50', 'Greek Delights', 4.3),
    ('flavor_fanatic', 'Greek Delights', 4.8),
    ('cheese_connoisseur', 'Greek Delights', 4.5),
    ('culinary_adventurer', 'Greek Delights', 4.7),
    ('mediterranean_meanderer', 'Greek Delights', 4.9),
    ('hot_sauce_hero', 'Greek Delights', 4.7),
    ('pizza_pal', 'Greek Delights', 4.6),
    ('dessert_diva', 'Greek Delights', 4.8),
    ('bakery_buff', 'Greek Delights', 4.5),

    ('hot_sauce_hero', 'Herbivore Hideout', 4.7),
    ('veggie_voyager', 'Herbivore Hideout', 4.9),
    ('herbivore_haven', 'Herbivore Hideout', 4.5),
    ('flavor_fanatic', 'Herbivore Hideout', 4.8),
    ('epicurean85', 'Herbivore Hideout', 4.6),

    ('noodle_navigator', 'Noodle Nirvana', 4.6),
    ('pasta_lover', 'Noodle Nirvana', 4.4),
    ('burger_buff', 'Noodle Nirvana', 4.7),
    ('tea_enthusiast', 'Noodle Nirvana', 4.5),
    ('epicurean85', 'Noodle Nirvana', 4.8),
    ('bbq_master', 'Noodle Nirvana', 3.3),
    ('flavor_fanatic', 'Noodle Nirvana', 4.8),
    ('breakfast_lover', 'Noodle Nirvana', 4.5),
    ('culinary_adventurer', 'Noodle Nirvana', 3.7),

    ('spice_seeker', 'Spicy Delights', 4.9),
    ('flavor_fanatic', 'Spicy Delights', 4.9),
    ('mediterranean_meanderer', 'Spicy Delights', 4.8),
    ('cheese_connoisseur', 'Spicy Delights', 4.9),
    ('spice_aficionado', 'Spicy Delights', 4.7),

    ('sweet_tooth', 'Sugar Rush', 4.9),
    ('dessert_diva', 'Sugar Rush', 4.7),
    ('flavor_fanatic', 'Sugar Rush', 4.8),
    ('juice_junkie', 'Sugar Rush', 4.6),
    ('bakery_buff', 'Sugar Rush', 4.5),

    ('sushi_sensei', 'Sushi Sensation', 4.7),
    ('dessert_diva', 'Sushi Sensation', 4.6),
    ('dimsum_devotee', 'Sushi Sensation', 4.5),
    ('seafood_seeker', 'Sushi Sensation', 4.8),
    ('gourmet_guru', 'Sushi Sensation', 4.9);