INSERT INTO Users (userName, userType, userPwd, resName)
VALUES
    ('admin', 'ADMIN', '1234', NULL),
    ('gourmet_guru', 'APPLICANT', '1234', 'Taco Palace'),
    ('epicurean85', 'SIGNED', '1234', NULL),
    ('pasta_lover', 'APPLICANT', '1234', 'Pasta Paradise'),
    ('flavor_fanatic', 'SIGNED', '1234', NULL),
    ('sushi_sensei', 'APPLICANT', '1234', 'Sushi Sensation'),
    ('mediterranean_meanderer', 'APPLICANT', '1234', 'Greek Delights'),
    ('fusion_fanatic', 'SIGNED', '1234', NULL),
    ('burger_buff', 'SIGNED', '1234', NULL),
    ('pizza_pal', 'SIGNED', '1234', NULL),
    ('dimsum_devotee', 'SIGNED', '1234', NULL),
    ('spice_seeker', 'APPLICANT', '1234', 'Spicy Delights'),
    ('taste_traveller', 'SIGNED', '1234', NULL),
    ('bbq_master', 'APPLICANT', '1234', 'Smokehouse BBQ'),
    ('coffee_craze', 'APPLICANT', '1234', 'Coffee Corner'),
    ('sweet_tooth', 'APPLICANT', '1234', 'Sugar Rush'),
    ('dessert_diva', 'SIGNED', '1234', NULL),
    ('veggie_voyager', 'SIGNED', '1234', NULL),
    ('hot_sauce_hero', 'APPLICANT', '1234', 'Fiery Bites'),
    ('breakfast_lover', 'APPLICANT', '1234', 'Rise & Shine Eats'),
    ('culinary_adventurer', 'SIGNED', '1234', NULL),
    ('noodle_navigator', 'APPLICANT', '1234', 'Noodle Nirvana'),
    ('cheese_connoisseur', 'SIGNED', '1234', NULL),
    ('herbivore_haven', 'APPLICANT', '1234', 'Herbivore Hideout'),
    ('seafood_seeker', 'APPLICANT', '1234', 'Ocean Bounty'),
    ('bakery_buff', 'SIGNED', '1234', NULL),
    ('tea_enthusiast', 'APPLICANT', '1234', 'Tea Temptations'),
    ('juice_junkie', 'SIGNED', '1234', NULL),
    ('farm_to_table', 'APPLICANT', '1234', 'Farm-to-Table Eats'),
    ('spice_aficionado', 'SIGNED', '1234', NULL),
    ('creative_user50', 'APPLICANT', '1234', 'Creative Cuisine');